### ISSUE TITLE
Library: History and Bookmarks on new tab page

### ISSUE THREAD

**Issue by chrmod** [cliqz/user-agent-ios#195]
We bring back the design from Cliqz 2.0 - that is, bookmarks list and history are "tabs" on New Tab Page.

- [ ] in new tab page you have 3 segment controls #197 
- [ ] Bookmarks: simple list with swipe to delete #198
- [ ] History: simple list segmented by date with swipe to delete #199
- [ ] segment settings #200 

 We rather implement it from scratch so we can remove Firefox library.

For the reference check Cliqz 2.0 from App Store.
