### ISSUE TITLE
Content Blocker issues for 3.0.0

### ISSUE THREAD

**Issue by chrmod** [cliqz/user-agent-ios#303]
This is a meta ticket to track adblocker-filters issue progress.

- [x] https://github.com/cliqz/adblocker-filters/issues/211
- [ ] https://github.com/cliqz/adblocker-filters/issues/210
- [x] https://github.com/cliqz/adblocker-filters/issues/253
- [ ] https://github.com/cliqz/adblocker-filters/issues/257
- [ ] https://github.com/cliqz/adblocker-filters/issues/279 
- [x] https://github.com/cliqz/adblocker-filters/issues/288
